id: P006643
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:12:27.685805
source_metadata:
  id: bdr:W29903
  title: སྐྱེས་རབས
  author: ''
  volumes:
    049297fa079847adbf2aab69bcbcdc3d:
      image_group_id: I5715
      title: ''
      volume_number: 1
      total_pages: 472
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
